bases:
- github.com/spinnaker/kustomization-base/base
secretGenerator:
- files:
  - kleat/clouddriver.yml
  name: clouddriver-config
  behavior: merge
- files: []
  name: spinnaker-secrets
  behavior: merge
